#!/bin/bash
# 2021-04-22
# Guillaume Le Treut

export CPLUS_INCLUDE_PATH=$CPLUS_INCLUDE_PATH_OLD
export LIBRARY_PATH=$LIBRARY_PATH_OLD
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH_OLD

echo CPLUS_INCLUDE_PATH=$CPLUS_INCLUDE_PATH
echo LIBRARY_PATH=$LIBRARY_PATH
echo LD_LIBRARY_PATH=$LD_LIBRARY_PATH
